<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: google/protobuf/type.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Field;

/**
 * @api
 *
 * Whether a field is optional, required, or repeated.
 */
enum Cardinality: int
{
    /** For fields with unknown cardinality. */
    case CARDINALITY_UNKNOWN = 0;

    /** For optional fields. */
    case CARDINALITY_OPTIONAL = 1;

    /** For required fields. Proto2 syntax only. */
    case CARDINALITY_REQUIRED = 2;

    /** For repeated fields. */
    case CARDINALITY_REPEATED = 3;
}
