<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: google/protobuf/type.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Field;

/**
 * @api
 *
 * Basic field types.
 */
enum Kind: int
{
    /** Field type unknown. */
    case TYPE_UNKNOWN = 0;

    /** Field type double. */
    case TYPE_DOUBLE = 1;

    /** Field type float. */
    case TYPE_FLOAT = 2;

    /** Field type int64. */
    case TYPE_INT64 = 3;

    /** Field type uint64. */
    case TYPE_UINT64 = 4;

    /** Field type int32. */
    case TYPE_INT32 = 5;

    /** Field type fixed64. */
    case TYPE_FIXED64 = 6;

    /** Field type fixed32. */
    case TYPE_FIXED32 = 7;

    /** Field type bool. */
    case TYPE_BOOL = 8;

    /** Field type string. */
    case TYPE_STRING = 9;

    /** Field type group. Proto2 syntax only, and deprecated. */
    case TYPE_GROUP = 10;

    /** Field type message. */
    case TYPE_MESSAGE = 11;

    /** Field type bytes. */
    case TYPE_BYTES = 12;

    /** Field type uint32. */
    case TYPE_UINT32 = 13;

    /** Field type enum. */
    case TYPE_ENUM = 14;

    /** Field type sfixed32. */
    case TYPE_SFIXED32 = 15;

    /** Field type sfixed64. */
    case TYPE_SFIXED64 = 16;

    /** Field type sint32. */
    case TYPE_SINT32 = 17;

    /** Field type sint64. */
    case TYPE_SINT64 = 18;
}
