<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: google/protobuf/api.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Api is a light-weight descriptor for an API Interface.
 *
 * Interfaces are also described as "protocol buffer services" in some contexts,
 * such as by the "service" keyword in a .proto file, but they are different
 * from API Services, which represent a concrete implementation of an interface
 * as opposed to simply a description of methods and bindings. They are also
 * sometimes simply referred to as "APIs" in other contexts, such as the name of
 * this message itself. See https://cloud.google.com/apis/design/glossary for
 * detailed terminology.
 *
 * New usages of this message as an alternative to ServiceDescriptorProto are
 * strongly discouraged. This message does not reliability preserve all
 * information necessary to model the schema and preserve semantics. Instead
 * make use of FileDescriptorSet which preserves the necessary information.
 */
final readonly class Api
{
    /**
     * @param string $name The fully qualified name of this interface, including package name
     * followed by the interface's simple name.
     * @param list<\Google\Protobuf\Method> $methods The methods of this interface, in unspecified order.
     * @param list<\Google\Protobuf\Option> $options Any metadata attached to the interface.
     * @param string $version A version string for this interface. If specified, must have the form
     * `major-version.minor-version`, as in `1.10`. If the minor version is
     * omitted, it defaults to zero. If the entire version field is empty, the
     * major version is derived from the package name, as outlined below. If the
     * field is not empty, the version in the package name will be verified to be
     * consistent with what is provided here.
     *
     * The versioning schema uses [semantic
     * versioning](http://semver.org) where the major version number
     * indicates a breaking change and the minor version an additive,
     * non-breaking change. Both version numbers are signals to users
     * what to expect from different versions, and should be carefully
     * chosen based on the product plan.
     *
     * The major version is also reflected in the package name of the
     * interface, which must end in `v<major-version>`, as in
     * `google.feature.v1`. For major versions 0 and 1, the suffix can
     * be omitted. Zero major versions must only be used for
     * experimental, non-GA interfaces.
     * @param ?\Google\Protobuf\SourceContext $sourceContext Source context for the protocol buffer service represented by this
     * message.
     * @param list<\Google\Protobuf\Mixin> $mixins Included interfaces. See [Mixin][].
     * @param \Google\Protobuf\Syntax $syntax The source syntax of the service.
     * @param string $edition The source edition string, only valid when syntax is SYNTAX_EDITIONS.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Method::class)))]
        public array $methods = [],
        #[Reflection\Field(3, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Option::class)))]
        public array $options = [],
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $version = '',
        #[Reflection\Field(5, new Reflection\ObjectT(\Google\Protobuf\SourceContext::class))]
        public ?\Google\Protobuf\SourceContext $sourceContext = null,
        #[Reflection\Field(6, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Mixin::class)))]
        public array $mixins = [],
        #[Reflection\Field(7, new Reflection\EnumT(\Google\Protobuf\Syntax::class))]
        public \Google\Protobuf\Syntax $syntax = \Google\Protobuf\Syntax::SYNTAX_PROTO2,
        #[Reflection\Field(8, Reflection\StringT::T)]
        public string $edition = '',
    ) {}
}
