<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 */

declare(strict_types=1);

\Thesis\Protobuf\Registry\Pool::get()->register(
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufAnyDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufApiDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufDurationDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufEmptyDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufFieldMaskDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufSourceContextDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufWrappersDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufStructDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufTimestampDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Protobuf\GoogleProtobufTypeDescriptorRegistry()),
);
