<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.16
 *   protoc               — v6.33.5
 * Source: google/protobuf/empty.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

/**
 * @api
 *
 * A generic empty message that you can re-use to avoid defining duplicated
 * empty messages in your APIs. A typical example is to use it as the request
 * or the response type of an API method. For instance:
 *
 *     service Foo {
 *       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
 *     }
 */
final readonly class Empty_ {}
