<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: google/protobuf/type.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Enum value definition.
 *
 * New usages of this message as an alternative to EnumValueDescriptorProto are
 * strongly discouraged. This message does not reliability preserve all
 * information necessary to model the schema and preserve semantics. Instead
 * make use of FileDescriptorSet which preserves the necessary information.
 */
final readonly class EnumValue
{
    /**
     * @param string $name Enum value name.
     * @param int $number Enum value number.
     * @param list<\Google\Protobuf\Option> $options Protocol buffer options.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public int $number = 0,
        #[Reflection\Field(3, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Option::class)))]
        public array $options = [],
    ) {}
}
