<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: google/protobuf/type.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Enum type definition.
 *
 * New usages of this message as an alternative to EnumDescriptorProto are
 * strongly discouraged. This message does not reliability preserve all
 * information necessary to model the schema and preserve semantics. Instead
 * make use of FileDescriptorSet which preserves the necessary information.
 */
final readonly class Enum
{
    /**
     * @param string $name Enum type name.
     * @param list<\Thesis\Google\Protobuf\EnumValue> $enumvalue Enum value definitions.
     * @param list<\Thesis\Google\Protobuf\Option> $options Protocol buffer options.
     * @param ?\Thesis\Google\Protobuf\SourceContext $sourceContext The source context.
     * @param \Thesis\Google\Protobuf\Syntax $syntax The source syntax.
     * @param string $edition The source edition string, only valid when syntax is SYNTAX_EDITIONS.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Thesis\Google\Protobuf\EnumValue::class)))]
        public array $enumvalue = [],
        #[Reflection\Field(3, new Reflection\ListT(new Reflection\ObjectT(\Thesis\Google\Protobuf\Option::class)))]
        public array $options = [],
        #[Reflection\Field(4, new Reflection\ObjectT(\Thesis\Google\Protobuf\SourceContext::class))]
        public ?\Thesis\Google\Protobuf\SourceContext $sourceContext = null,
        #[Reflection\Field(5, new Reflection\EnumT(\Thesis\Google\Protobuf\Syntax::class))]
        public \Thesis\Google\Protobuf\Syntax $syntax = \Thesis\Google\Protobuf\Syntax::SYNTAX_PROTO2,
        #[Reflection\Field(6, Reflection\StringT::T)]
        public string $edition = '',
    ) {}
}
