<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.23
 *   protoc               — v6.33.5
 * Source: google/protobuf/type.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A single field of a message type.
 *
 * New usages of this message as an alternative to FieldDescriptorProto are
 * strongly discouraged. This message does not reliability preserve all
 * information necessary to model the schema and preserve semantics. Instead
 * make use of FileDescriptorSet which preserves the necessary information.
 */
final readonly class Field
{
    /**
     * @param \Google\Protobuf\Field\Kind $kind The field type.
     * @param \Google\Protobuf\Field\Cardinality $cardinality The field cardinality.
     * @param int $number The field number.
     * @param string $name The field name.
     * @param string $typeUrl The field type URL, without the scheme, for message or enumeration
     * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
     * @param int $oneofIndex The index of the field type in `Type.oneofs`, for message or enumeration
     * types. The first type has index 1; zero means the type is not in the list.
     * @param bool $packed Whether to use alternative packed wire representation.
     * @param list<\Google\Protobuf\Option> $options The protocol buffer options.
     * @param string $jsonName The field JSON name.
     * @param string $defaultValue The string value of the default value of this field. Proto2 syntax only.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Google\Protobuf\Field\Kind::class))]
        public \Google\Protobuf\Field\Kind $kind = \Google\Protobuf\Field\Kind::TYPE_UNKNOWN,
        #[Reflection\Field(2, new Reflection\EnumT(\Google\Protobuf\Field\Cardinality::class))]
        public \Google\Protobuf\Field\Cardinality $cardinality = \Google\Protobuf\Field\Cardinality::CARDINALITY_UNKNOWN,
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public int $number = 0,
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(6, Reflection\StringT::T)]
        public string $typeUrl = '',
        #[Reflection\Field(7, Reflection\Int32T::T)]
        public int $oneofIndex = 0,
        #[Reflection\Field(8, Reflection\BoolT::T)]
        public bool $packed = false,
        #[Reflection\Field(9, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Option::class)))]
        public array $options = [],
        #[Reflection\Field(10, Reflection\StringT::T)]
        public string $jsonName = '',
        #[Reflection\Field(11, Reflection\StringT::T)]
        public string $defaultValue = '',
    ) {}
}
