<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.1
 *   protoc               — v6.33.5
 * Source: google/protobuf/wrappers.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Wrapper message for `int64`.
 *
 * The JSON representation for `Int64Value` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
final readonly class Int64Value
{
    /**
     * @param int $value The int64 value.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public int $value = 0,
    ) {}
}
