<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.32.1
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * `ListValue` is a wrapper around a repeated field of values.
 *
 * The JSON representation for `ListValue` is JSON array.
 */
final readonly class ListValue
{
    /**
     * @param list<\Google\Protobuf\Value> $values Repeated field of dynamically typed values.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Value::class)))]
        public array $values = [],
    ) {}
}
