<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.0
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * `ListValue` is a wrapper around a repeated field of values.
 *
 * The JSON representation for `ListValue` is JSON array.
 */
final readonly class ListValue
{
    /**
     * @param list<\Thesis\Google\Protobuf\Value> $values Repeated field of dynamically typed values.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\Thesis\Google\Protobuf\Value::class)))]
        public array $values = [],
    ) {}
}
