<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.16
 *   protoc               — v6.33.5
 * Source: google/protobuf/api.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Method represents a method of an API interface.
 *
 * New usages of this message as an alternative to MethodDescriptorProto are
 * strongly discouraged. This message does not reliability preserve all
 * information necessary to model the schema and preserve semantics. Instead
 * make use of FileDescriptorSet which preserves the necessary information.
 */
final readonly class Method
{
    /**
     * @param string $name The simple name of this method.
     * @param string $requestTypeUrl A URL of the input message type.
     * @param bool $requestStreaming If true, the request is streamed.
     * @param string $responseTypeUrl The URL of the output message type.
     * @param bool $responseStreaming If true, the response is streamed.
     * @param list<\Google\Protobuf\Option> $options Any metadata attached to the method.
     * @param ?\Google\Protobuf\Syntax $syntax The source syntax of this method.
     *
     * This field should be ignored, instead the syntax should be inherited from
     * Api. This is similar to Field and EnumValue.
     * @param string $edition The source edition string, only valid when syntax is SYNTAX_EDITIONS.
     *
     * This field should be ignored, instead the edition should be inherited from
     * Api. This is similar to Field and EnumValue.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $requestTypeUrl = '',
        #[Reflection\Field(3, Reflection\BoolT::T)]
        public bool $requestStreaming = false,
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $responseTypeUrl = '',
        #[Reflection\Field(5, Reflection\BoolT::T)]
        public bool $responseStreaming = false,
        #[Reflection\Field(6, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Option::class)))]
        public array $options = [],
        #[Reflection\Field(7, new Reflection\EnumT(\Google\Protobuf\Syntax::class))]
        public ?\Google\Protobuf\Syntax $syntax = null,
        #[Reflection\Field(8, Reflection\StringT::T)]
        public string $edition = '',
    ) {}
}
