<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

/**
 * @api
 *
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 *
 * The JSON representation for `NullValue` is JSON `null`.
 */
enum NullValue: int
{
    /** Null value. */
    case NULL_VALUE = 0;
}
