<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/source_context.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * `SourceContext` represents information about the source of a
 * protobuf element, like the file in which it is defined.
 */
final readonly class SourceContext
{
    /**
     * @param string $fileName The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $fileName = '',
    ) {}
}
