<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf;
use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * `Struct` represents a structured data value, consisting of fields
 * which map to dynamically typed values. In some languages, `Struct`
 * might be supported by a native representation. For example, in
 * scripting languages like JS a struct is represented as an
 * object. The details of that representation are described together
 * with the proto support for the language.
 *
 * The JSON representation for `Struct` is JSON object.
 */
final readonly class Struct
{
    /**
     * @param Protobuf\Map<string, \Google\Protobuf\Value> $fields Unordered map of dynamically typed values.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\MapT(Reflection\StringT::T, new Reflection\ObjectT(\Google\Protobuf\Value::class)))]
        public Protobuf\Map $fields = new Protobuf\Map(),
    ) {}
}
