<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: google/protobuf/type.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

/**
 * @api
 *
 * The syntax in which a protocol buffer element is defined.
 */
enum Syntax: int
{
    /** Syntax `proto2`. */
    case SYNTAX_PROTO2 = 0;

    /** Syntax `proto3`. */
    case SYNTAX_PROTO3 = 1;

    /** Syntax `editions`. */
    case SYNTAX_EDITIONS = 2;
}
