<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.32.1
 * Source: google/protobuf/type.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A protocol buffer message type.
 *
 * New usages of this message as an alternative to DescriptorProto are strongly
 * discouraged. This message does not reliability preserve all information
 * necessary to model the schema and preserve semantics. Instead make use of
 * FileDescriptorSet which preserves the necessary information.
 */
final readonly class Type
{
    /**
     * @param string $name The fully qualified message name.
     * @param list<\Google\Protobuf\Field> $fields The list of fields.
     * @param list<string> $oneofs The list of types appearing in `oneof` definitions in this type.
     * @param list<\Google\Protobuf\Option> $options The protocol buffer options.
     * @param ?\Google\Protobuf\SourceContext $sourceContext The source context.
     * @param ?\Google\Protobuf\Syntax $syntax The source syntax.
     * @param string $edition The source edition string, only valid when syntax is SYNTAX_EDITIONS.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Field::class)))]
        public array $fields = [],
        #[Reflection\Field(3, new Reflection\ListT(Reflection\StringT::T))]
        public array $oneofs = [],
        #[Reflection\Field(4, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Option::class)))]
        public array $options = [],
        #[Reflection\Field(5, new Reflection\ObjectT(\Google\Protobuf\SourceContext::class))]
        public ?\Google\Protobuf\SourceContext $sourceContext = null,
        #[Reflection\Field(6, new Reflection\EnumT(\Google\Protobuf\Syntax::class))]
        public ?\Google\Protobuf\Syntax $syntax = null,
        #[Reflection\Field(7, Reflection\StringT::T)]
        public string $edition = '',
    ) {}
}
