<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.23
 *   protoc               — v6.33.5
 * Source: google/protobuf/wrappers.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Wrapper message for `uint32`.
 *
 * The JSON representation for `UInt32Value` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
final readonly class UInt32Value
{
    /**
     * @param int $value The uint32 value.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Uint32T::T)]
        public int $value = 0,
    ) {}
}
