<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * `Value` represents a dynamically typed value which can be either
 * null, a number, a string, a boolean, a recursive struct value, or a
 * list of values. A producer of value is expected to set one of these
 * variants. Absence of any variant indicates an error.
 *
 * The JSON representation for `Value` is JSON value.
 */
final readonly class Value
{
    public function __construct(
        #[Reflection\OneOf([
            \Thesis\Google\Protobuf\Value\KindNullValue::class,
            \Thesis\Google\Protobuf\Value\KindNumberValue::class,
            \Thesis\Google\Protobuf\Value\KindStringValue::class,
            \Thesis\Google\Protobuf\Value\KindBoolValue::class,
            \Thesis\Google\Protobuf\Value\KindStructValue::class,
            \Thesis\Google\Protobuf\Value\KindListValue::class,
        ])]
        public ?\Thesis\Google\Protobuf\Value\Kind $kind = null,
    ) {}
}
