<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Protobuf\Value;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindNullValue implements \Thesis\Google\Protobuf\Value\Kind
{
    /**
     * @param \Thesis\Google\Protobuf\NullValue $nullValue Represents a null value.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Thesis\Google\Protobuf\NullValue::class))]
        public \Thesis\Google\Protobuf\NullValue $nullValue = \Thesis\Google\Protobuf\NullValue::NULL_VALUE,
    ) {}
}
