<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Value;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindNullValue implements \Google\Protobuf\Value\Kind
{
    /**
     * @param \Google\Protobuf\NullValue $nullValue Represents a null value.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Google\Protobuf\NullValue::class))]
        public \Google\Protobuf\NullValue $nullValue = \Google\Protobuf\NullValue::NULL_VALUE,
    ) {}
}
