<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Value;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindStringValue implements \Google\Protobuf\Value\Kind
{
    /**
     * @param string $stringValue Represents a string value.
     */
    public function __construct(
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $stringValue = '',
    ) {}
}
