<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Value;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindListValue implements \Google\Protobuf\Value\Kind
{
    /**
     * @param ?\Google\Protobuf\ListValue $listValue Represents a repeated `Value`.
     */
    public function __construct(
        #[Reflection\Field(6, new Reflection\ObjectT(\Google\Protobuf\ListValue::class))]
        public ?\Google\Protobuf\ListValue $listValue = null,
    ) {}
}
