<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.23
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Value;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindStructValue implements \Google\Protobuf\Value\Kind
{
    /**
     * @param ?\Google\Protobuf\Struct $structValue Represents a structured value.
     */
    public function __construct(
        #[Reflection\Field(5, new Reflection\ObjectT(\Google\Protobuf\Struct::class))]
        public ?\Google\Protobuf\Struct $structValue = null,
    ) {}
}
