<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.0
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Protobuf\Value;

/**
 * @api
 * @phpstan-sealed (
 *   KindNullValue |
 *   KindNumberValue |
 *   KindStringValue |
 *   KindBoolValue |
 *   KindStructValue |
 *   KindListValue
 * )
 */
interface Kind {}
