<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Value;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindNumberValue implements \Google\Protobuf\Value\Kind
{
    /**
     * @param float $numberValue Represents a double value.
     */
    public function __construct(
        #[Reflection\Field(2, Reflection\DoubleT::T)]
        public float $numberValue = 0,
    ) {}
}
