<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: google/protobuf/struct.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Value;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindBoolValue implements \Google\Protobuf\Value\Kind
{
    /**
     * @param bool $boolValue Represents a boolean value.
     */
    public function __construct(
        #[Reflection\Field(4, Reflection\BoolT::T)]
        public bool $boolValue = false,
    ) {}
}
